config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users


  resources :users
  resources :articolis

  get 'home',        to: 'home#index'
  get 'gallery',     to: 'home#gallery'
  get 'project',     to: 'home#project'
  get 'chisiamo',    to: 'home#chisiamo'
  get 'percorsi',    to: 'home#percorsi', as: 'percorsi'
  get 'prodotti',    to: 'home#prodotti', as: 'prodotti'


  get 'click/:pagina',      to: 'home#click', as: 'click'
  get 'home/like/:pagina',  to: 'home#click', as: 'like_click'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/articoli.rb
class Articoli < ApplicationRecord
    has_one_attached :cover
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/articolis_controller.rb
class ArticolisController < ApplicationController
  before_action :set_channel, only: %i[ show edit update destroy]
  before_action :authenticate_user!, except: %i[ show ]
  before_action :set_articoli, only: %i[ show edit update destroy ]

  # GET /articolis or /articolis.json
  def index
    @articolis = Articoli.all
  end

  # GET /articolis/1 or /articolis/1.json
  def show
  end

  # GET /articolis/new
  def new
    @articoli = Articoli.new
  end

  # GET /articolis/1/edit
  def edit
  end

  # POST /articolis or /articolis.json
  def create
    @articoli = Articoli.new(articoli_params)

    respond_to do |format|
      if @articoli.save
        format.html { redirect_to @articoli, notice: "Articoli was successfully created." }
        format.json { render :show, status: :created, location: @articoli }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @articoli.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articolis/1 or /articolis/1.json
  def update
    respond_to do |format|
      if @articoli.update(articoli_params)
        format.html { redirect_to @articoli, notice: "Articoli was successfully updated." }
        format.json { render :show, status: :ok, location: @articoli }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @articoli.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articolis/1 or /articolis/1.json
  def destroy
    @articoli.destroy!

    respond_to do |format|
      format.html { redirect_to articolis_path, status: :see_other, notice: "Articoli was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_articoli
      @articoli = Articoli.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def articoli_params
      params.expect(articoli: [ :titolo, :descrizione, :prezzo, :cover])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
      @like_home = Like.find_by(pagina: 'home')&.click || 0
      @like_gallery = Like.find_by(pagina: 'gallery')&.click || 0
      @like_percorsi = Like.find_by(pagina: 'percorsi')&.click || 0
      @like_staff = Like.find_by(pagina: 'chisiamo')&.click || 0
      @like_prodotti = Like.find_by(pagina: 'prodotti')&.click || 0
    end

    def gallery
      @like_home = Like.find_by(pagina: 'home')&.click || 0
      @like_gallery = Like.find_by(pagina: 'gallery')&.click || 0
      @like_percorsi = Like.find_by(pagina: 'percorsi')&.click || 0
      @like_staff = Like.find_by(pagina: 'chisiamo')&.click || 0
      @like_prodotti = Like.find_by(pagina: 'prodotti')&.click || 0
    end

    def project
      @like_home = Like.find_by(pagina: 'home')&.click || 0
      @like_gallery = Like.find_by(pagina: 'gallery')&.click || 0
      @like_percorsi = Like.find_by(pagina: 'percorsi')&.click || 0
      @like_staff = Like.find_by(pagina: 'chisiamo')&.click || 0
      @like_prodotti = Like.find_by(pagina: 'prodotti')&.click || 0
    end

    def chisiamo
      @like_home = Like.find_by(pagina: 'home')&.click || 0
      @like_gallery = Like.find_by(pagina: 'gallery')&.click || 0
      @like_percorsi = Like.find_by(pagina: 'percorsi')&.click || 0
      @like_staff = Like.find_by(pagina: 'chisiamo')&.click || 0
      @like_prodotti = Like.find_by(pagina: 'prodotti')&.click || 0
    end

    def percorsi 
      @like_home = Like.find_by(pagina: 'home')&.click || 0
      @like_gallery = Like.find_by(pagina: 'gallery')&.click || 0
      @like_percorsi = Like.find_by(pagina: 'percorsi')&.click || 0
      @like_staff = Like.find_by(pagina: 'chisiamo')&.click || 0
      @like_prodotti = Like.find_by(pagina: 'prodotti')&.click || 0
    end

    def prodotti 
      @like_home = Like.find_by(pagina: 'home')&.click || 0
      @like_gallery = Like.find_by(pagina: 'gallery')&.click || 0
      @like_percorsi = Like.find_by(pagina: 'percorsi')&.click || 0
      @like_staff = Like.find_by(pagina: 'chisiamo')&.click || 0
      @like_prodotti = Like.find_by(pagina: 'prodotti')&.click || 0
    end

    def click
        like = Like.find_by(pagina: params[:pagina])
        
        if like
          like.click += 1
          if like.click == 20
            like.click = 0
          end
          like.save
          redirect_to send("#{like.pagina}_path")
        else
          flash[:error] = "La pagina non esiste."
          redirect_to root_path
        end
      end
    end
    

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_path, status: :see_other, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.expect(user: [ :email, :admin ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articolis_helper.rb
module ArticolisHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articolis/_articoli.html.erb
<div id="<%= dom_id articoli %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Titolo:</strong>
    <%= articoli.titolo %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Descrizione:</strong>
    <%= articoli.descrizione %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Prezzo:</strong>
    <%= articoli.prezzo %>
  </p>
  <p>
    <% if articoli.cover.attached? %>
      <%= image_tag url_for(articoli.cover), class: 'w-100', style: 'max-width: 300px;' %>
    <% end %>
  </p>
</div>

app/views/articolis/_form.html.erb
<%= form_with(model: articoli, class: "contents") do |form| %>
  <% if articoli.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(articoli.errors.count, "error") %> prohibited this articoli from being saved:</h2>

      <ul class="list-disc ml-6">
        <% articoli.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :titolo %>
    <%= form.text_field :titolo, class: ["block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": articoli.errors[:titolo].none?, "border-red-400 focus:outline-red-600": articoli.errors[:titolo].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :descrizione %>
    <%= form.textarea :descrizione, rows: 4, class: ["block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": articoli.errors[:descrizione].none?, "border-red-400 focus:outline-red-600": articoli.errors[:descrizione].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :prezzo %>
    <%= form.number_field :prezzo, class: ["block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": articoli.errors[:prezzo].none?, "border-red-400 focus:outline-red-600": articoli.errors[:prezzo].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label 'Copertina', class: 'form-label'%>
    <%= form.file_field :cover, class: 'form-control'%>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/articolis/edit.html.erb
<% content_for :title, "Editing articoli" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing articoli</h1>

  <%= render "form", articoli: @articoli %>

  <%= link_to "Show this articoli", @articoli, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to articolis", articolis_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/articolis/index.html.erb
<% content_for :title, "Articolis" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Articolis</h1>
    <%= link_to "New articoli", new_articoli_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="articolis" class="min-w-full">
    <% if @articolis.any? %>
      <% @articolis.each do |articoli| %>
        <%= render articoli %>
        <p>
          <%= link_to "Show this articoli", articoli, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
        </p>
      <% end %>
    <% else %>
      <p class="text-center my-10">No articolis found.</p>
    <% end %>
  </div>
</div>

app/views/articolis/new.html.erb
<% content_for :title, "New articoli" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New articoli</h1>

  <%= render "form", articoli: @articoli %>

  <%= link_to "Back to articolis", articolis_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/articolis/show.html.erb
<% content_for :title, "Show prodotto" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Show prodotto</h1>

  <h2>Articoli del prodotto:</h2>
  <ul>
    <% @prodotto.articoli.each do |articolo| %>
      <li><%= link_to articolo.titolo, articolo_path(articolo) %></li>
    <% end %>
  </ul>

  <%= link_to "New articolo", new_prodotto_articolo_path(@prodotto), class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
</div>

app/views/home/_card.html.erb
<div class="container mx-auto py-16">
  <!-- Titolo e Sottotitolo sopra le Card -->
  <div class="mb-12">
    <div class="flex items-center">
      <h2 class="text-2xl font-thin text-gray-500">I nostri</h2>
      <h2 class="text-2xl font-bold text-gray-800 ml-2">Progetti</h2>
    </div>
  </div>

  <div class="flex flex-col gap-8">
    <!-- Card 1 -->
    <div class="flex flex-col md:flex-row items-center p-0 rounded-lg">
      <div class="w-full md:w-2/3 relative">
        <img src="https://www.alpecimbra.it/images/content/99473_12051_2_C_1170_657_0_1420138/win-fatbike-2016-neve-bike-art-01-fileminimizer-.jpg" alt="Immagine Card 1" class="w-full h-[435px] object-cover">
      </div>
      <div class="w-full md:w-1/3 bg-gray-50 p-6 rounded-lg h-[435px]">
        <h3 class="text-xl font-thin text-gray-500">Snow & Rocks: Il Giro della Montagna Congelata</h3>
        <p class="text-sm text-black mt-4">Pedalare su sentieri ghiacciati e ripidi, con discesa ad alta velocità tra rocce e neve. Un'esperienza estrema su una montagna di oltre 3000 metri, con gomme chiodate e temperature gelide.</p>
        <a href="#" class="mt-6 inline-flex items-center px-6 py-3 bg-white text-gray-800 text-lg hover:bg-gray-200 transition-all duration-300 rounded">
          <span>Vedi altro</span>
          <svg class="w-6 h-6 ml-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 12H5m14 0-4 4m4-4-4-4"/>
          </svg>
        </a>
      </div>
    </div>

    <!-- Card 2 -->
    <div class="flex flex-col md:flex-row items-center p-0 rounded-lg">
      <div class="w-full md:w-2/3 relative">
        <img src="https://www.bikedivision.it/DesktopModules/DigArticle/MediaHandler.ashx?portalid=30&moduleid=2765&mediaid=4842" alt="Immagine Card 2" class="w-full h-[435px] object-cover">
      </div>
      <div class="w-full md:w-1/3 bg-gray-50 p-6 rounded-lg h-[435px]">
        <h3 class="text-xl font-thin text-gray-500">Skyline Madness: Pedalata tra i Grattacieli</h3>
        <p class="text-sm text-black mt-4">Un percorso urbano con rampe e salti tra tetti e terrazze. I ciclisti eseguono trick incredibili, sfiorando il vuoto e atterrando su passerelle sospese tra i palazzi!</p>
        <a href="#" class="mt-6 inline-flex items-center px-6 py-3 bg-white text-gray-800 text-lg hover:bg-gray-200 transition-all duration-300 rounded">
          <span>Vedi altro</span>
          <svg class="w-6 h-6 ml-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 12H5m14 0-4 4m4-4-4-4"/>
          </svg>
        </a>
      </div>
    </div>

    <!-- Card 3 -->
    <div class="flex flex-col md:flex-row items-center p-0 rounded-lg">
      <div class="w-full md:w-2/3 relative">
        <img src="https://guidevulcanologicheetna.it/wp-content/uploads/2022/12/informazioni-sui-percorsi-in-mountain-bike-e-e-bike-sullEtna-1080x675.jpg" alt="Immagine Card 3" class="w-full h-[435px] object-cover">
      </div>
      <div class="w-full md:w-1/3 bg-gray-50 p-6 rounded-lg h-[435px]">
        <h3 class="text-xl font-thin text-gray-500">Into the Abyss: La Discesa nel Vulcano</h3>
        <p class="text-sm text-black mt-4">Un viaggio dentro un cratere vulcanico spento, tra sabbia nera e tunnel di lava solidificata. Curve strette, pendenze impossibili e una corsa folle fino al cuore della Terra!</p>
        <a href="#" class="mt-6 inline-flex items-center px-6 py-3 bg-white text-gray-800 text-lg hover:bg-gray-200 transition-all duration-300 rounded">
          <span>Vedi altro</span>
          <svg class="w-6 h-6 ml-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 12H5m14 0-4 4m4-4-4-4"/>
          </svg>
        </a>
      </div>
    </div>
  </div>
</div>

app/views/home/_contact.html.erb
<div class="container mx-auto py-16 px-4 md:px-8 grid grid-cols-1 md:grid-cols-2 items-center gap-8">
  <!-- Modulo di contatto -->
  <div class="bg-white p-8 rounded-lg">
    <h2 class="text-gray-700 text-4xl font-light mb-6">Contattaci</h2>
    <form action="#" method="POST" class="space-y-4">
      <input type="text" placeholder="Nome" class="w-full p-3 border border-gray-300 rounded bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-400">
      <input type="tel" placeholder="Numero di Telefono" class="w-full p-3 border border-gray-300 rounded bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-400">
      <input type="email" placeholder="E-mail *" class="w-full p-3 border border-gray-300 rounded bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-400">
      <input type="text" placeholder="Interessato a" class="w-full p-3 border border-gray-300 rounded bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-400">
      <textarea placeholder="Messaggio" rows="4" class="w-full p-3 border border-gray-300 rounded bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-400"></textarea>
      <button type="submit" class="bg-black text-white px-6 py-3 rounded text-lg hover:bg-gray-800 transition-all duration-300">Invia Email →</button>
    </form>
  </div>
  
  <!-- Immagine -->
  <div class="h-full">
    <img src="https://www.rossignolproshop.com/wp-content/uploads/2022/06/e-bike-mtb3.jpg" alt="Biker in Montagna" class="w-full h-full object-cover rounded-lg shadow-lg">
  </div>
</div>

app/views/home/_goals.html.erb
<div class="container mx-auto py-16">
  <h1 class="text-5xl font-bold text-gray-300 text-center mb-12">I Nostri Obiettivi</h1>
  <div class="flex flex-col md:flex-row items-center md:space-x-8 mb-12">
    <div class="flex items-center md:w-1/2 mb-8 md:mb-0">
      <div class="text-8xl font-bold text-gray-300 mr-6">1</div>
      <p class="text-lg text-gray-600">Affrontare percorsi unici e spettacolari, spingendo i limiti del ciclismo in ambienti insoliti come montagne innevate, vulcani o scenari urbani estremi.</p>
    </div>
    <div class="flex items-center md:w-1/2">
      <div class="text-8xl font-bold text-gray-300 mr-6">2</div>
      <p class="text-lg text-gray-600">Superare ostacoli naturali e artificiali, eseguire acrobazie e testare resistenza, tecnica e coraggio in situazioni fuori dal comune.</p>
    </div>
  </div>
</div>

app/views/home/chisiamo.html.erb
<%= render 'home/maps' %>

app/views/home/gallery.html.erb
<%= render 'home/photo' %>

app/views/home/index.html.erb
<%= render 'home/header' %>
<%= render 'home/sezions'%>
<%= render 'home/wedo' %>
<%= render 'home/goals' %>
<%= render 'home/project' %>
<%= render 'home/contact' %>

app/views/home/percorsi.html.erb
<%= render 'home/card' %>

app/views/home/prodotti.html.erb
<%= render 'views/form' %>

app/views/layouts/_navbar.html.erb
<nav class="bg-white py-4 shadow-md">
  <div class="container mx-auto flex items-center justify-between">
    
    <!-- Logo -->
    <div>
      <%= link_to root_path do %>
        <img src="https://www.creativefabrica.com/wp-content/uploads/2018/11/Bicycle-bike-logo-by-DEEMKA-STUDIO-1-580x406.jpg" alt="Bike Adventures Logo" class="h-16 w-auto">
      <% end %>
    </div>

    <!-- Menu -->
    <ul class="flex space-x-8 text-gray-700 font-roboto uppercase pr-64 items-center">
      <!-- Home -->
      <li class="relative">
        <span class="absolute top-[-14px] left-1/2 transform -translate-x-1/2 bg-black text-white text-[10px] font-bold px-2 py-[2px] rounded-full shadow-lg">
          <%= @like_home %>
        </span>
        <%= link_to "Home", root_path, class: "relative block px-5 py-2 border-b-2 border-gray-900 text-center rounded-md transition-all duration-300 hover:bg-gray-900 hover:text-white" %>
      </li>

      <!-- Galleria -->
      <li class="relative">
        <span class="absolute top-[-14px] left-1/2 transform -translate-x-1/2 bg-black text-white text-[10px] font-bold px-2 py-[2px] rounded-full shadow-lg">
          <%= @like_gallery %>
        </span>
        <%= link_to "Galleria", gallery_path, class: "relative block px-5 py-2 border-b-2 border-gray-900 text-center rounded-md transition-all duration-300 hover:bg-gray-900 hover:text-white" %>
      </li>

      <!-- Percorsi -->
      <li class="relative">
        <span class="absolute top-[-14px] left-1/2 transform -translate-x-1/2 bg-black text-white text-[10px] font-bold px-2 py-[2px] rounded-full shadow-lg">
          <%= @like_percorsi %>
        </span>
        <%= link_to "Percorsi", percorsi_path, class: "relative block px-5 py-2 border-b-2 border-gray-900 text-center rounded-md transition-all duration-300 hover:bg-gray-900 hover:text-white" %>
      </li>

      <!-- Chi siamo -->
      <li class="relative">
        <span class="absolute top-[-14px] left-1/2 transform -translate-x-1/2 bg-black text-white text-[10px] font-bold px-2 py-[2px] rounded-full shadow-lg">
          <%= @like_staff %>
        </span>
        <%= link_to "Chi siamo", chisiamo_path, class: "relative block px-5 py-2 border-b-2 border-gray-900 text-center rounded-md transition-all duration-300 hover:bg-gray-900 hover:text-white" %>
      </li>

      <!-- Prodotti -->
      <li class="relative">
        <span class="absolute top-[-14px] left-1/2 transform -translate-x-1/2 bg-black text-white text-[10px] font-bold px-2 py-[2px] rounded-full shadow-lg">
          <%= @like_prodotti %>
        </span>
        <%= link_to "Prodotti", articolis_path, class: "relative block px-5 py-2 border-b-2 border-gray-900 text-center rounded-md transition-all duration-300 hover:bg-gray-900 hover:text-white" %>

      </li>

      <!-- Auth buttons -->
      <% if user_signed_in? %>
        <li>
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "bg-red-600 text-white font-bold px-4 py-2 rounded-md hover:bg-red-700 transition-all duration-300" %>
        </li>
      <% else %>
        <li>
          <%= link_to 'Login / Registrati', new_user_session_path, class: "bg-blue-600 text-white font-bold px-4 py-2 rounded-md hover:bg-blue-700 transition-all duration-300" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Email:</strong>
    <%= user.email %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Admin:</strong>
    <%= user.admin %>
  </p>
</div>

app/views/users/edit.html.erb
<% content_for :title, "Editing user" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing user</h1>

  <%= render "form", user: @user %>

  <%= link_to "Show this user", @user, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to users", users_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/users/index.html.erb
<% content_for :title, "Users" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Users</h1>
    <%= link_to "New user", new_user_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="users" class="min-w-full">
    <% if @users.any? %>
      <% @users.each do |user| %>
        <%= render user %>
        <p>
          <%= link_to "Show this user", user, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
        </p>
      <% end %>
    <% else %>
      <p class="text-center my-10">No users found.</p>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% content_for :title, "Showing user" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing user</h1>

  <%= render @user %>

  <%= link_to "Edit this user", edit_user_path(@user), class: "mt-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to users", users_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <div class="inline-block ml-2">
    <%= button_to "Destroy this user", @user, method: :delete, class: "mt-2 rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium" %>
  </div>
</div>